version: "3.8"

services:
    db:
        image: postgres
        env_file:
            - ./env/postgres.env
        volumes:
            - dbdata:/var/lib/postgresql/data
        container_name: fb_postgresdb
        restart: always

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - ./backend/src:/app/src
            - ./backend/prisma:/app/prisma
        ports:
            - 4000:4000
        env_file:
            - ./env/backend.env
        environment:
            CHOKIDAR_USEPOLLING: "true"
        container_name: fb_backend
        depends_on:
            - db

    prisma:
        depends_on:
            - db
        container_name: prisma
        ports:
            - '5555:5555'
        build:
            context: backend/prisma
            dockerfile: Dockerfile
        env_file:
            - ./env/backend.env
        volumes:
            - ./backend/prisma:/app/prisma

    frontend:
        stdin_open: true
        tty: true
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend/src:/app/src
        ports:
            - 3000:3000
        environment:
            - WDS_SOCKET_HOST=127.0.0.1 
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
        container_name: fb_frontend
        depends_on:
            - backend

volumes:
    dbdata:
