import { Box, Flex, Stack } from "@chakra-ui/react";
import React from "react";
import { IntroBio } from "./ui";
import { ContentContainer } from "@/ui";

export const Posts = () => {
	return (
		<Flex gap={4}>
			<Box as="aside" flexBasis="40%">
				<Stack gap={2} mb={4}>
					<ContentContainer>
						<>TITE</>
					</ContentContainer>
					<IntroBio />
					<IntroBio />
				</Stack>
				<ContentContainer
					position="sticky"
					top={-10}
					height={1000}
					mb={4}
				>
					<>TITE</>
				</ContentContainer>
			</Box>

			<Stack flexBasis="60%">
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>

				<ContentContainer>
					<></>
				</ContentContainer>
				<ContentContainer>
					<></>
				</ContentContainer>
			</Stack>
		</Flex>
	);
};
