name: Test and Build Backend app

on:
    pull_request:
        branches:
            [] # Don't trigger workflow for now
            # - main
        paths:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
            - uses: actions/setup-node@v2
              with:
                  cache: "yarn"

            - name: Install dependencies
              run: |
                  yarn install

            - name: Run tests
              run: |
                  yarn test
